# Basic dependabot.yml file with
# minimum configuration for two package managers

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"
  - package-ecosystem: "npm"
    directory: "/client"
    schedule:
      interval: "weekly"
      day: "thursday"
      timezone: "Europe/Amsterdam"
    open-pull-requests-limit: 1
    commit-message:
      prefix: "npm"
    labels:
      - "npm"
      - "dependencies"